---
title: "Graphs"
author: "Xavier Marquez"
date: "2023-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(targets)
library(tidyverse)
```

## Combined Graphs


```{r fig-graph_sims_svd_word_vectors_decade_dfm_50_ppmi_nn}
#| fig-cap: sims svd word vectors decade dfm 50 ppmi, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_sims_svd_word_vectors_decade_dfm_50_ppmi)

graph[[2]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_50_ppmi_vb}
#| fig-cap: sims svd word vectors decade dfm 50 ppmi, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_50_ppmi_jj}
#| fig-cap: sims svd word vectors decade dfm 50 ppmi, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_50_ppmi_ism}
#| fig-cap: sims svd word vectors decade dfm 50 ppmi, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_50_ppmi_uppercase_nouns}
#| fig-cap: sims svd word vectors decade dfm 50 ppmi, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_sims_svd_word_vectors_decade_dfm_random_50_ppmi_nn}
#| fig-cap: sims svd word vectors decade dfm random 50 ppmi, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_sims_svd_word_vectors_decade_dfm_random_50_ppmi)

graph[[2]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_random_50_ppmi_vb}
#| fig-cap: sims svd word vectors decade dfm random 50 ppmi, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_random_50_ppmi_jj}
#| fig-cap: sims svd word vectors decade dfm random 50 ppmi, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_random_50_ppmi_ism}
#| fig-cap: sims svd word vectors decade dfm random 50 ppmi, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_random_50_ppmi_uppercase_nouns}
#| fig-cap: sims svd word vectors decade dfm random 50 ppmi, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_sims_svd_word_vectors_decade_dfm_similarity_50_ppmi_nn}
#| fig-cap: sims svd word vectors decade dfm similarity 50 ppmi, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_sims_svd_word_vectors_decade_dfm_similarity_50_ppmi)

graph[[2]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_similarity_50_ppmi_vb}
#| fig-cap: sims svd word vectors decade dfm similarity 50 ppmi, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_similarity_50_ppmi_jj}
#| fig-cap: sims svd word vectors decade dfm similarity 50 ppmi, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_similarity_50_ppmi_ism}
#| fig-cap: sims svd word vectors decade dfm similarity 50 ppmi, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_sims_svd_word_vectors_decade_dfm_similarity_50_ppmi_uppercase_nouns}
#| fig-cap: sims svd word vectors decade dfm similarity 50 ppmi, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_nn}
#| fig-cap: weights predictive classification decade dfm glmnet, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_weights_predictive_classification_decade_dfm_glmnet)

graph[[2]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_vb}
#| fig-cap: weights predictive classification decade dfm glmnet, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_jj}
#| fig-cap: weights predictive classification decade dfm glmnet, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_ism}
#| fig-cap: weights predictive classification decade dfm glmnet, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_uppercase_nouns}
#| fig-cap: weights predictive classification decade dfm glmnet, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_random_nn}
#| fig-cap: weights predictive classification decade dfm glmnet random, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_weights_predictive_classification_decade_dfm_glmnet_random)

graph[[2]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_random_vb}
#| fig-cap: weights predictive classification decade dfm glmnet random, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_random_jj}
#| fig-cap: weights predictive classification decade dfm glmnet random, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_random_ism}
#| fig-cap: weights predictive classification decade dfm glmnet random, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_random_uppercase_nouns}
#| fig-cap: weights predictive classification decade dfm glmnet random, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_similarity_nn}
#| fig-cap: weights predictive classification decade dfm glmnet similarity, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_weights_predictive_classification_decade_dfm_glmnet_similarity)

graph[[2]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_similarity_vb}
#| fig-cap: weights predictive classification decade dfm glmnet similarity, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_similarity_jj}
#| fig-cap: weights predictive classification decade dfm glmnet similarity, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_similarity_ism}
#| fig-cap: weights predictive classification decade dfm glmnet similarity, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_glmnet_similarity_uppercase_nouns}
#| fig-cap: weights predictive classification decade dfm glmnet similarity, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_nn}
#| fig-cap: weights predictive classification decade dfm LiblineaR, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_weights_predictive_classification_decade_dfm_LiblineaR)

graph[[2]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_vb}
#| fig-cap: weights predictive classification decade dfm LiblineaR, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_jj}
#| fig-cap: weights predictive classification decade dfm LiblineaR, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_ism}
#| fig-cap: weights predictive classification decade dfm LiblineaR, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_uppercase_nouns}
#| fig-cap: weights predictive classification decade dfm LiblineaR, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_random_nn}
#| fig-cap: weights predictive classification decade dfm LiblineaR random, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_weights_predictive_classification_decade_dfm_LiblineaR_random)

graph[[2]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_random_vb}
#| fig-cap: weights predictive classification decade dfm LiblineaR random, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_random_jj}
#| fig-cap: weights predictive classification decade dfm LiblineaR random, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_random_ism}
#| fig-cap: weights predictive classification decade dfm LiblineaR random, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_random_uppercase_nouns}
#| fig-cap: weights predictive classification decade dfm LiblineaR random, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_similarity_nn}
#| fig-cap: weights predictive classification decade dfm LiblineaR similarity, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_weights_predictive_classification_decade_dfm_LiblineaR_similarity)

graph[[2]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_similarity_vb}
#| fig-cap: weights predictive classification decade dfm LiblineaR similarity, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_similarity_jj}
#| fig-cap: weights predictive classification decade dfm LiblineaR similarity, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_similarity_ism}
#| fig-cap: weights predictive classification decade dfm LiblineaR similarity, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_LiblineaR_similarity_uppercase_nouns}
#| fig-cap: weights predictive classification decade dfm LiblineaR similarity, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_nn}
#| fig-cap: weights predictive classification decade dfm xgboost, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_weights_predictive_classification_decade_dfm_xgboost)

graph[[2]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_vb}
#| fig-cap: weights predictive classification decade dfm xgboost, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_jj}
#| fig-cap: weights predictive classification decade dfm xgboost, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_ism}
#| fig-cap: weights predictive classification decade dfm xgboost, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_uppercase_nouns}
#| fig-cap: weights predictive classification decade dfm xgboost, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_random_nn}
#| fig-cap: weights predictive classification decade dfm xgboost random, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_weights_predictive_classification_decade_dfm_xgboost_random)

graph[[2]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_random_vb}
#| fig-cap: weights predictive classification decade dfm xgboost random, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_random_jj}
#| fig-cap: weights predictive classification decade dfm xgboost random, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_random_ism}
#| fig-cap: weights predictive classification decade dfm xgboost random, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_random_uppercase_nouns}
#| fig-cap: weights predictive classification decade dfm xgboost random, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_similarity_nn}
#| fig-cap: weights predictive classification decade dfm xgboost similarity, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_weights_predictive_classification_decade_dfm_xgboost_similarity)

graph[[2]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_similarity_vb}
#| fig-cap: weights predictive classification decade dfm xgboost similarity, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_similarity_jj}
#| fig-cap: weights predictive classification decade dfm xgboost similarity, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_similarity_ism}
#| fig-cap: weights predictive classification decade dfm xgboost similarity, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_weights_predictive_classification_decade_dfm_xgboost_similarity_uppercase_nouns}
#| fig-cap: weights predictive classification decade dfm xgboost similarity, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_ppmi_single_decade_dfm_nn}
#| fig-cap: ppmi single decade dfm, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_ppmi_single_decade_dfm)

graph[[2]]

```

 
```{r fig-graph_ppmi_single_decade_dfm_vb}
#| fig-cap: ppmi single decade dfm, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_ppmi_single_decade_dfm_jj}
#| fig-cap: ppmi single decade dfm, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_ppmi_single_decade_dfm_ism}
#| fig-cap: ppmi single decade dfm, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_ppmi_single_decade_dfm_uppercase_nouns}
#| fig-cap: ppmi single decade dfm, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```


```{r fig-graph_sims_ppmi_decade_dfm_nn}
#| fig-cap: sims ppmi decade dfm, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graph_sims_ppmi_decade_dfm)

graph[[2]]

```

 
```{r fig-graph_sims_ppmi_decade_dfm_vb}
#| fig-cap: sims ppmi decade dfm, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[3]]

```

 
```{r fig-graph_sims_ppmi_decade_dfm_jj}
#| fig-cap: sims ppmi decade dfm, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[4]]

```

 
```{r fig-graph_sims_ppmi_decade_dfm_ism}
#| fig-cap: sims ppmi decade dfm, -ism terms only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[5]]

```

 
```{r fig-graph_sims_ppmi_decade_dfm_uppercase_nouns}
#| fig-cap: sims ppmi decade dfm, nouns starting with uppercase only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9


graph[[6]]

```

## Model performance graphs

```{r fig-combined_performance_graph_classification_auc}
#| fig-cap: "Predictive performance of classification models, AUC measure."
#| fig-width: 9


tar_load(combined_performance)

combined_performance %>% 
  dplyr::filter(stringr::str_detect(.metric, "auc")) %>%
  dplyr::mutate(sampling_type = dplyr::case_when(stringr::str_detect(source, "_random") ~ 
                                                   "Downsampled majority class, at random",
                                                 stringr::str_detect(source, "_similarity") ~ 
                                                   "Downsampled majority class, \nmost similar texts by PPMI",
                                                 TRUE ~ "No downsampling")) %>%
  ggplot2::ggplot(ggplot2::aes( x= decade, y = .estimate, color = model_type, alpha = forcats::fct_rev(sample))) + 
  ggplot2::geom_point() + 
  ggplot2::geom_line() + 
  ggplot2::facet_wrap( ~ sampling_type) +
  ggplot2::theme_bw() +
  ggplot2::labs(alpha = "Sample", color = "Model") +
  theme(legend.position = "bottom")+
  guides(colour = guide_legend(nrow = 2),
         alpha = guide_legend(nrow = 2))

```
```{r fig-combined_performance_graph_classification_acc}
#| fig-cap: "Predictive performance of classification models, accuracy measure."
#| fig-width: 9

combined_performance %>% 
  dplyr::filter(stringr::str_detect(.metric, "accuracy")) %>%
  dplyr::mutate(sampling_type = dplyr::case_when(stringr::str_detect(source, "_random") ~ 
                                                   "Downsampled majority class, at random",
                                                 stringr::str_detect(source, "_similarity") ~ 
                                                   "Downsampled majority class, \nmost similar texts by PPMI",
                                                 TRUE ~ "No downsampling")) %>%
  ggplot2::ggplot(ggplot2::aes( x= decade, y = .estimate, color = model_type, alpha = forcats::fct_rev(sample))) + 
  ggplot2::geom_point() + 
  ggplot2::geom_line() + 
  ggplot2::facet_wrap( ~ sampling_type) +
  ggplot2::theme_bw() +
  ggplot2::labs(alpha = "Sample", color = "Model") +
  theme(legend.position = "bottom") +
  guides(colour = guide_legend(nrow = 3),
         alpha = guide_legend(nrow = 2))
```

```{r fig-combined_performance_graph_classification_kap}
#| fig-cap: "Predictive performance of classification models, Cohen's Kappa measure."
#| fig-width: 9

combined_performance %>% 
  dplyr::filter(stringr::str_detect(.metric, "kap")) %>%
  dplyr::mutate(sampling_type = dplyr::case_when(stringr::str_detect(source, "_random") ~ 
                                                   "Downsampled majority class, at random",
                                                 stringr::str_detect(source, "_similarity") ~ 
                                                   "Downsampled majority class, \nmost similar texts by PPMI",
                                                 TRUE ~ "No downsampling")) %>%
  ggplot2::ggplot(ggplot2::aes( x= decade, y = .estimate, color = model_type, alpha = forcats::fct_rev(sample))) + 
  ggplot2::geom_point() + 
  ggplot2::geom_line() + 
  ggplot2::facet_wrap( ~ sampling_type) +
  ggplot2::theme_bw() +
  ggplot2::labs(alpha = "Sample", color = "Model") +
  theme(legend.position = "bottom") +
  guides(colour = guide_legend(nrow = 2),
         alpha = guide_legend(nrow = 2))
```


```{r fig-combined_performance_graph_classification_log_loss}
#| fig-cap: "Predictive performance of classification models, log loss measure."
#| fig-width: 9

combined_performance %>% 
  dplyr::filter(stringr::str_detect(.metric, "deviance|mae|mn|mse")) %>%
  dplyr::mutate(sampling_type = dplyr::case_when(stringr::str_detect(source, "_random") ~ 
                                                   "Downsampled majority class, at random",
                                                 stringr::str_detect(source, "_similarity") ~ 
                                                   "Downsampled majority class, \nmost similar texts by PPMI",
                                                 TRUE ~ "No downsampling")) %>%
  ggplot2::ggplot(ggplot2::aes( x= decade, y = .estimate, color = model_type, 
                                shape = .metric, alpha = forcats::fct_rev(sample))) + 
  ggplot2::geom_point() + 
  ggplot2::geom_line() + 
  ggplot2::facet_wrap( ~ sampling_type) +
  ggplot2::theme_bw() +
  ggplot2::labs(alpha = "Sample", color = "Model") +
  theme(legend.position = "bottom") +
  guides(colour = guide_legend(nrow = 2),
         alpha = guide_legend(nrow = 2),
         shape = guide_legend(nrow = 2))
```

