#!/bin/bash
# Proxy sacct to the Slurm submit host over ssh (see slurm/shims/sbatch).
exec ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new "${DEMAGOGUES_SUBMIT_HOST:-${SLURM_SUBMIT_HOST:-raapoi.vuw.ac.nz}}" sacct "$@"
