
```{r fig-graphs_58a29ed93ac719fc483e29726a78a893}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_58a29ed93ac719fc483e29726a78a893)

graph

```



```{r fig-graphs_829f6e4f19cc31435f87adab9c701082}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_829f6e4f19cc31435f87adab9c701082)

graph

```



```{r fig-graphs_2697506a95928b1f47286ad5ee451202}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_2697506a95928b1f47286ad5ee451202)

graph

```



```{r fig-graphs_68ff94f02fe39526264ad74f2b0eab5f}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_68ff94f02fe39526264ad74f2b0eab5f)

graph

```



```{r fig-graphs_8dba4d2bac1bd72f7b849e627a74689c}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_8dba4d2bac1bd72f7b849e627a74689c)

graph

```



```{r fig-graphs_e49bc8bfe48224174873f84417a70525}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_e49bc8bfe48224174873f84417a70525)

graph

```



```{r fig-graphs_d9c3be6cddf151efdd79b4f4a4a987b4}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, no downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_d9c3be6cddf151efdd79b4f4a4a987b4)

graph

```



```{r fig-graphs_3aeede41146616af3f7ff7aaff9884ed}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_3aeede41146616af3f7ff7aaff9884ed)

graph

```



```{r fig-graphs_9889d3a58fd257b656ea01bfbe024da1}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_9889d3a58fd257b656ea01bfbe024da1)

graph

```



```{r fig-graphs_7ffd7d220ad92683ff3b33df87ad99ab}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_7ffd7d220ad92683ff3b33df87ad99ab)

graph

```



```{r fig-graphs_dc81976b3600e463c5b74524d0882faf}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_dc81976b3600e463c5b74524d0882faf)

graph

```



```{r fig-graphs_ce86b5219256657d8ba61c9e81f7b82a}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_ce86b5219256657d8ba61c9e81f7b82a)

graph

```



```{r fig-graphs_69a0796995964d78a772d7f0a9d3a04c}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_69a0796995964d78a772d7f0a9d3a04c)

graph

```



```{r fig-graphs_f0fc287447549632b487f800d1ce5c20}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_f0fc287447549632b487f800d1ce5c20)

graph

```



```{r fig-graphs_9ab2093063a3d1d187914fc07d9b7658}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_9ab2093063a3d1d187914fc07d9b7658)

graph

```



```{r fig-graphs_34db7cf76cf4b5884f984ca8c048bc00}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_34db7cf76cf4b5884f984ca8c048bc00)

graph

```



```{r fig-graphs_4a7300d7bcbf861e0a495cc6afd77244}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_4a7300d7bcbf861e0a495cc6afd77244)

graph

```



```{r fig-graphs_5acf4910679459b95856f3d64a231bee}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, no downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_5acf4910679459b95856f3d64a231bee)

graph

```



```{r fig-graphs_cf501799ce7b997f08259d2951d9ca6f}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_cf501799ce7b997f08259d2951d9ca6f)

graph

```



```{r fig-graphs_170a884d2e825b0c5167aeb666a9e343}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_170a884d2e825b0c5167aeb666a9e343)

graph

```



```{r fig-graphs_3f2aa417e393245e251e63f4d7b81f06}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_3f2aa417e393245e251e63f4d7b81f06)

graph

```



```{r fig-graphs_fda59dd175b681760f3b04c5527d4707}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_fda59dd175b681760f3b04c5527d4707)

graph

```



```{r fig-graphs_4b9becc02da6a924ee558421a2c2d06d}
#| fig-cap: Single-feature PPMI to target feature, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_4b9becc02da6a924ee558421a2c2d06d)

graph

```



```{r fig-graphs_413acdc2af97943b3dfd5238f69e86d0}
#| fig-cap: Single-feature PPMI to target feature, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_413acdc2af97943b3dfd5238f69e86d0)

graph

```



```{r fig-graphs_07b5c0b79fb562a0be8a3ac431aef604}
#| fig-cap: Single-feature PPMI to target feature, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_07b5c0b79fb562a0be8a3ac431aef604)

graph

```



```{r fig-graphs_048dd5deb0935c4c49f91e3516a3bb68}
#| fig-cap: Single-feature PPMI to target feature, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_048dd5deb0935c4c49f91e3516a3bb68)

graph

```



```{r fig-graphs_7a12b66f7ec712d9e606decc96a8ee48}
#| fig-cap: Single-feature PPMI to target feature, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_7a12b66f7ec712d9e606decc96a8ee48)

graph

```



```{r fig-graphs_eac40e375c464dc5b9fb2f08c2697939}
#| fig-cap: Single-feature PPMI to target feature, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_eac40e375c464dc5b9fb2f08c2697939)

graph

```



```{r fig-graphs_5dce6b4a34b96c7573263959c88292d7}
#| fig-cap: Single-feature PPMI to target feature, no downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_5dce6b4a34b96c7573263959c88292d7)

graph

```



```{r fig-graphs_219d3e8457ac842f1682716bb0bad340}
#| fig-cap: Single-feature PPMI to target feature, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_219d3e8457ac842f1682716bb0bad340)

graph

```



```{r fig-graphs_3671147596e184b4bb3cdbdaca42a7d0}
#| fig-cap: Single-feature PPMI to target feature, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_3671147596e184b4bb3cdbdaca42a7d0)

graph

```



```{r fig-graphs_3aaee70ab09e09979485f5b9ac9e7f71}
#| fig-cap: Single-feature PPMI to target feature, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_3aaee70ab09e09979485f5b9ac9e7f71)

graph

```



```{r fig-graphs_c982c43c4326ed90e19f18f438085ea4}
#| fig-cap: Single-feature PPMI to target feature, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_c982c43c4326ed90e19f18f438085ea4)

graph

```



```{r fig-graphs_19d5baf8e1663ef30aa4dbaa7efc9cb2}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_19d5baf8e1663ef30aa4dbaa7efc9cb2)

graph

```



```{r fig-graphs_1e5b93f51106656a1a7e5699f282f771}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_1e5b93f51106656a1a7e5699f282f771)

graph

```



```{r fig-graphs_4e472ad21fc31fdd5d7fe2e7fde1aaf0}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_4e472ad21fc31fdd5d7fe2e7fde1aaf0)

graph

```



```{r fig-graphs_2ff37951cdbd883acb30b81e485dc750}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_2ff37951cdbd883acb30b81e485dc750)

graph

```



```{r fig-graphs_63d0ab314db04e74e5d443823c0c972d}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_63d0ab314db04e74e5d443823c0c972d)

graph

```



```{r fig-graphs_801967cb1f4a645eb0c26f06e006994b}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_801967cb1f4a645eb0c26f06e006994b)

graph

```



```{r fig-graphs_96d4e5ddc69577c7699327209bdc2981}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, random downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_96d4e5ddc69577c7699327209bdc2981)

graph

```



```{r fig-graphs_8c93974bd55f44d931dde19c996bc0f9}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_8c93974bd55f44d931dde19c996bc0f9)

graph

```



```{r fig-graphs_a5bd5be5a19505ddc4ab09c67a68846e}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_a5bd5be5a19505ddc4ab09c67a68846e)

graph

```



```{r fig-graphs_3faf15f78f6cb2e507d5f4e5ec1528db}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_3faf15f78f6cb2e507d5f4e5ec1528db)

graph

```



```{r fig-graphs_62b8553e120a10a733adcd4089933fcc}
#| fig-cap: Cosine similarity to target feature across PPMI-weighted DFM, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_62b8553e120a10a733adcd4089933fcc)

graph

```



```{r fig-graphs_ab494c229500375870992e0adf89913c}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_ab494c229500375870992e0adf89913c)

graph

```



```{r fig-graphs_cf8dde365d0d4c58c91d1993a2c634ee}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_cf8dde365d0d4c58c91d1993a2c634ee)

graph

```



```{r fig-graphs_15bfd7c92673d30c328e1ea05554b1fc}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_15bfd7c92673d30c328e1ea05554b1fc)

graph

```



```{r fig-graphs_f3113f358dc2b3b7e5c5c2443efa2a2a}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_f3113f358dc2b3b7e5c5c2443efa2a2a)

graph

```



```{r fig-graphs_82d3d8639a227e9b10c5506af3dea6ec}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_82d3d8639a227e9b10c5506af3dea6ec)

graph

```



```{r fig-graphs_732b305925e8019d9162391df423a35d}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_732b305925e8019d9162391df423a35d)

graph

```



```{r fig-graphs_8df0b4003e3383b88ec3487925b0cb04}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, random downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_8df0b4003e3383b88ec3487925b0cb04)

graph

```



```{r fig-graphs_7f33fb7ee71451d4941516fb67317d5e}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_7f33fb7ee71451d4941516fb67317d5e)

graph

```



```{r fig-graphs_6d054ddd2998ffae2ce577ec1660059c}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_6d054ddd2998ffae2ce577ec1660059c)

graph

```



```{r fig-graphs_1222904e0ce90cb9bd8e2a30680ac14b}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_1222904e0ce90cb9bd8e2a30680ac14b)

graph

```



```{r fig-graphs_fa83accc31fedcddbe5e06656b73dd88}
#| fig-cap: Cosine similarity to target term in SVD word vector space, PPMI weights, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_fa83accc31fedcddbe5e06656b73dd88)

graph

```



```{r fig-graphs_c099abe064a2bcef0cd1ef90024171ca}
#| fig-cap: Single-feature PPMI to target feature, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_c099abe064a2bcef0cd1ef90024171ca)

graph

```



```{r fig-graphs_cfaac868deb45287a1e61a03403ba560}
#| fig-cap: Single-feature PPMI to target feature, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_cfaac868deb45287a1e61a03403ba560)

graph

```



```{r fig-graphs_5de12ce68791b03fc6cf8743fbb2d1e7}
#| fig-cap: Single-feature PPMI to target feature, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_5de12ce68791b03fc6cf8743fbb2d1e7)

graph

```



```{r fig-graphs_b4ae6d4fd9e1b9c6cbbc4000d8c7697f}
#| fig-cap: Single-feature PPMI to target feature, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_b4ae6d4fd9e1b9c6cbbc4000d8c7697f)

graph

```



```{r fig-graphs_7e377e3ca0bcb81140c9d47b3d555f57}
#| fig-cap: Single-feature PPMI to target feature, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_7e377e3ca0bcb81140c9d47b3d555f57)

graph

```



```{r fig-graphs_afd0b5ba3c865d5cc5b339460845a636}
#| fig-cap: Single-feature PPMI to target feature, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_afd0b5ba3c865d5cc5b339460845a636)

graph

```



```{r fig-graphs_d771850211f47483ee59756bc6d7741b}
#| fig-cap: Single-feature PPMI to target feature, random downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_d771850211f47483ee59756bc6d7741b)

graph

```



```{r fig-graphs_433268b09b9ed0151e6d8f40b71794a8}
#| fig-cap: Single-feature PPMI to target feature, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_433268b09b9ed0151e6d8f40b71794a8)

graph

```



```{r fig-graphs_36f62202633598d0777909261e5cb004}
#| fig-cap: Single-feature PPMI to target feature, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_36f62202633598d0777909261e5cb004)

graph

```



```{r fig-graphs_4187bf84705ad7a89fadd6563459e180}
#| fig-cap: Single-feature PPMI to target feature, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_4187bf84705ad7a89fadd6563459e180)

graph

```



```{r fig-graphs_45118d76d287e7cd97cf4bdaa80d393c}
#| fig-cap: Single-feature PPMI to target feature, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_45118d76d287e7cd97cf4bdaa80d393c)

graph

```



```{r fig-graphs_01a9987a06c5b1bf1983dc7327b4abe9}
#| fig-cap: Coefficients of logistic regression, glmnet, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_01a9987a06c5b1bf1983dc7327b4abe9)

graph

```



```{r fig-graphs_441dbd54d0726000cac0c265dc672722}
#| fig-cap: Coefficients of logistic regression, glmnet, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_441dbd54d0726000cac0c265dc672722)

graph

```



```{r fig-graphs_22e7537a03ad184ac1cf6f0c2beb42f2}
#| fig-cap: Coefficients of logistic regression, glmnet, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_22e7537a03ad184ac1cf6f0c2beb42f2)

graph

```



```{r fig-graphs_9ec2cbf223fb18a9524303231a4851ac}
#| fig-cap: Coefficients of logistic regression, glmnet, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_9ec2cbf223fb18a9524303231a4851ac)

graph

```



```{r fig-graphs_f7904460e50221853208c40798d84d2b}
#| fig-cap: Coefficients of logistic regression, glmnet, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_f7904460e50221853208c40798d84d2b)

graph

```



```{r fig-graphs_781a78d15a657fa8bedc1e09541993ff}
#| fig-cap: Coefficients of logistic regression, glmnet, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_781a78d15a657fa8bedc1e09541993ff)

graph

```



```{r fig-graphs_8bbb2ddd0eb3fc00d9fd6dbf0d89b9b6}
#| fig-cap: Coefficients of logistic regression, glmnet, no downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_8bbb2ddd0eb3fc00d9fd6dbf0d89b9b6)

graph

```



```{r fig-graphs_4f32ce0cfc0cb0396bca1d9b8896396b}
#| fig-cap: Coefficients of logistic regression, glmnet, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_4f32ce0cfc0cb0396bca1d9b8896396b)

graph

```



```{r fig-graphs_b243d358bb58dbc0278e62797d92dc5c}
#| fig-cap: Coefficients of logistic regression, glmnet, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_b243d358bb58dbc0278e62797d92dc5c)

graph

```



```{r fig-graphs_e759683eb40c0e074823e7cca34685cd}
#| fig-cap: Coefficients of logistic regression, glmnet, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_e759683eb40c0e074823e7cca34685cd)

graph

```



```{r fig-graphs_16bbacd10f258ad58ac500d98ea6c129}
#| fig-cap: Coefficients of logistic regression, glmnet, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_16bbacd10f258ad58ac500d98ea6c129)

graph

```



```{r fig-graphs_ec7204ad84ab56b3a6392d59060b26c0}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_ec7204ad84ab56b3a6392d59060b26c0)

graph

```



```{r fig-graphs_dfa84d0fc1cfe04421cf9d6908a1062c}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_dfa84d0fc1cfe04421cf9d6908a1062c)

graph

```



```{r fig-graphs_6f0291229c29a7e93d97a351a2448eee}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_6f0291229c29a7e93d97a351a2448eee)

graph

```



```{r fig-graphs_4c6af60807fb1cd9625d6a42734681c9}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_4c6af60807fb1cd9625d6a42734681c9)

graph

```



```{r fig-graphs_e712281e5fd6b0831ad39fe7e8a81bf0}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_e712281e5fd6b0831ad39fe7e8a81bf0)

graph

```



```{r fig-graphs_2ece1148b0da26a819aceb2f7c7ac9b4}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_2ece1148b0da26a819aceb2f7c7ac9b4)

graph

```



```{r fig-graphs_5f99e8ca6838dcc61480a12b4b2e1266}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, no downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_5f99e8ca6838dcc61480a12b4b2e1266)

graph

```



```{r fig-graphs_1cedc1463791aa4c765bd7cad9333150}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_1cedc1463791aa4c765bd7cad9333150)

graph

```



```{r fig-graphs_57aa1b04dfba413d0c0d6c5e61179747}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_57aa1b04dfba413d0c0d6c5e61179747)

graph

```



```{r fig-graphs_7e2dee1e990a6e1c735a1136e42997cd}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_7e2dee1e990a6e1c735a1136e42997cd)

graph

```



```{r fig-graphs_9b3f9a05612b9bc1e969c06c7ccbbc10}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_9b3f9a05612b9bc1e969c06c7ccbbc10)

graph

```



```{r fig-graphs_fd8a7e1661f330ee03ab8162a8158d45}
#| fig-cap: Weights of SVM model, LiblineaR, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_fd8a7e1661f330ee03ab8162a8158d45)

graph

```



```{r fig-graphs_48d6b4faa896a34fe7f85f93578d8939}
#| fig-cap: Weights of SVM model, LiblineaR, no downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_48d6b4faa896a34fe7f85f93578d8939)

graph

```



```{r fig-graphs_275cfe683ee2005316d37fc66f79512e}
#| fig-cap: Weights of SVM model, LiblineaR, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_275cfe683ee2005316d37fc66f79512e)

graph

```



```{r fig-graphs_7215e07b09b9b6885db1063add373ef7}
#| fig-cap: Weights of SVM model, LiblineaR, no downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_7215e07b09b9b6885db1063add373ef7)

graph

```



```{r fig-graphs_200e1fef262a4f623c7f809bd7f340e9}
#| fig-cap: Weights of SVM model, LiblineaR, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_200e1fef262a4f623c7f809bd7f340e9)

graph

```



```{r fig-graphs_116e12229ae769abf0cee29932e84b2c}
#| fig-cap: Weights of SVM model, LiblineaR, no downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_116e12229ae769abf0cee29932e84b2c)

graph

```



```{r fig-graphs_36d2f8fe94bdb7202cea8e8c5d6bdd79}
#| fig-cap: Weights of SVM model, LiblineaR, no downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_36d2f8fe94bdb7202cea8e8c5d6bdd79)

graph

```



```{r fig-graphs_325ff91260d4ecb252567d5ddd91439d}
#| fig-cap: Weights of SVM model, LiblineaR, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_325ff91260d4ecb252567d5ddd91439d)

graph

```



```{r fig-graphs_93232f990292a52488c5110c32af5600}
#| fig-cap: Weights of SVM model, LiblineaR, no downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_93232f990292a52488c5110c32af5600)

graph

```



```{r fig-graphs_b37ffa2220ac99d4dec06a6f1f95e29d}
#| fig-cap: Weights of SVM model, LiblineaR, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_b37ffa2220ac99d4dec06a6f1f95e29d)

graph

```



```{r fig-graphs_a8fa29a4d7d93734e67cc499f0be0310}
#| fig-cap: Weights of SVM model, LiblineaR, no downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_a8fa29a4d7d93734e67cc499f0be0310)

graph

```



```{r fig-graphs_8984d99cbb3317c6449bf0cd60dd8d1d}
#| fig-cap: Coefficients of logistic regression, glmnet, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_8984d99cbb3317c6449bf0cd60dd8d1d)

graph

```



```{r fig-graphs_b5cc276903245ee7b99a024e6923c709}
#| fig-cap: Coefficients of logistic regression, glmnet, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_b5cc276903245ee7b99a024e6923c709)

graph

```



```{r fig-graphs_c9b92727b9374c105fb27dfc22a70df6}
#| fig-cap: Coefficients of logistic regression, glmnet, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_c9b92727b9374c105fb27dfc22a70df6)

graph

```



```{r fig-graphs_42c1fc109138b0b76a9c3ded8ebe7766}
#| fig-cap: Coefficients of logistic regression, glmnet, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_42c1fc109138b0b76a9c3ded8ebe7766)

graph

```



```{r fig-graphs_b02abb24f11737d3b33349cfc181781f}
#| fig-cap: Coefficients of logistic regression, glmnet, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_b02abb24f11737d3b33349cfc181781f)

graph

```



```{r fig-graphs_fabab123fd3ec7ec997a81d582f90bb6}
#| fig-cap: Coefficients of logistic regression, glmnet, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_fabab123fd3ec7ec997a81d582f90bb6)

graph

```



```{r fig-graphs_6c739f4d21623fa1a8d1b2909df203b4}
#| fig-cap: Coefficients of logistic regression, glmnet, random downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_6c739f4d21623fa1a8d1b2909df203b4)

graph

```



```{r fig-graphs_5229360a2da40a1b5d8edf53dc7e2079}
#| fig-cap: Coefficients of logistic regression, glmnet, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_5229360a2da40a1b5d8edf53dc7e2079)

graph

```



```{r fig-graphs_64e2cf1bb5d4de472b13916b9d991fb5}
#| fig-cap: Coefficients of logistic regression, glmnet, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_64e2cf1bb5d4de472b13916b9d991fb5)

graph

```



```{r fig-graphs_64a377ef5d80a077e83372b1303b2821}
#| fig-cap: Coefficients of logistic regression, glmnet, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_64a377ef5d80a077e83372b1303b2821)

graph

```



```{r fig-graphs_3cf23afd1c8a61d62b6c5e10397ba922}
#| fig-cap: Coefficients of logistic regression, glmnet, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_3cf23afd1c8a61d62b6c5e10397ba922)

graph

```



```{r fig-graphs_62d0f95429d1efe3794ffc2ec83b84d8}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_62d0f95429d1efe3794ffc2ec83b84d8)

graph

```



```{r fig-graphs_2408a754034d05cd73c0f56efe19dd10}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_2408a754034d05cd73c0f56efe19dd10)

graph

```



```{r fig-graphs_6cadbb5553a8febe784555cdcc066698}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_6cadbb5553a8febe784555cdcc066698)

graph

```



```{r fig-graphs_ec659b204cb4578186bfd076f4c6a078}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_ec659b204cb4578186bfd076f4c6a078)

graph

```



```{r fig-graphs_0efd2c1e7b1839376c4ea5cf73bd780f}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_0efd2c1e7b1839376c4ea5cf73bd780f)

graph

```



```{r fig-graphs_6c2b94610d67ea8c4384fcebfc74b6ca}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_6c2b94610d67ea8c4384fcebfc74b6ca)

graph

```



```{r fig-graphs_382318321818669b3ee6aed81cec80ea}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, random downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_382318321818669b3ee6aed81cec80ea)

graph

```



```{r fig-graphs_9260ad95b1163e2c49637c64a01012df}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_9260ad95b1163e2c49637c64a01012df)

graph

```



```{r fig-graphs_33ea2a9b9b384cfd536f54e1c3ecb88f}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_33ea2a9b9b384cfd536f54e1c3ecb88f)

graph

```



```{r fig-graphs_3f7f65f0f2989abaef701d2d37242460}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_3f7f65f0f2989abaef701d2d37242460)

graph

```



```{r fig-graphs_99c9f2e3590ed34987b2b5e859194dbb}
#| fig-cap: Weights of gradient-boosted random forest model, xgboost, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_99c9f2e3590ed34987b2b5e859194dbb)

graph

```



```{r fig-graphs_53f25ad3b308263a1c23069194e65bc7}
#| fig-cap: Weights of SVM model, LiblineaR, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_53f25ad3b308263a1c23069194e65bc7)

graph

```



```{r fig-graphs_1fef42fef7fcbb46029b41fc80e33e4a}
#| fig-cap: Weights of SVM model, LiblineaR, random downsampling, adjectives only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_1fef42fef7fcbb46029b41fc80e33e4a)

graph

```



```{r fig-graphs_e689e42ba16ce341ad9aa4125c2bb903}
#| fig-cap: Weights of SVM model, LiblineaR, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_e689e42ba16ce341ad9aa4125c2bb903)

graph

```



```{r fig-graphs_29a54a8868a6eeed6738125accef3a0d}
#| fig-cap: Weights of SVM model, LiblineaR, random downsampling, all POS. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_29a54a8868a6eeed6738125accef3a0d)

graph

```



```{r fig-graphs_31b8593d37b9908ef0a3533e76c94b34}
#| fig-cap: Weights of SVM model, LiblineaR, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_31b8593d37b9908ef0a3533e76c94b34)

graph

```



```{r fig-graphs_de1878007b2a38bae27cedf23b2b6561}
#| fig-cap: Weights of SVM model, LiblineaR, random downsampling, nouns only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_de1878007b2a38bae27cedf23b2b6561)

graph

```



```{r fig-graphs_735f9d144e60371480b6cc0c22493dff}
#| fig-cap: Weights of SVM model, LiblineaR, random downsampling, terms beginning with uppercase. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_735f9d144e60371480b6cc0c22493dff)

graph

```



```{r fig-graphs_892bd41c857d146ee638679edda40fb3}
#| fig-cap: Weights of SVM model, LiblineaR, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_892bd41c857d146ee638679edda40fb3)

graph

```



```{r fig-graphs_a36557df8ca61a9bb3e38a67f4d8133b}
#| fig-cap: Weights of SVM model, LiblineaR, random downsampling, verbs only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_a36557df8ca61a9bb3e38a67f4d8133b)

graph

```



```{r fig-graphs_ab6b1a8999305c351228bcaa018c20c8}
#| fig-cap: Weights of SVM model, LiblineaR, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_ab6b1a8999305c351228bcaa018c20c8)

graph

```



```{r fig-graphs_bdcb96dbaab6816b26460ae5cf231a12}
#| fig-cap: Weights of SVM model, LiblineaR, random downsampling, words ending in ism only. Terms at the top are more closely associated with 'democracy' in later years. Label indicates the peak density of association.
#| fig-height: 9
graph <- tar_read(graphs_bdcb96dbaab6816b26460ae5cf231a12)

graph

```


